---
- name: Copy ip_routes script into place.
  template: src=ip_routes.j2 dest=/etc/ip_routes.sh owner=root group=root mode=0600

- name: Add systemd service to execute routes
  template: src=setup_routes.service.j2 dest=/etc/systemd/system/setup_routes.service owner=root group=root mode=0600

- name: enable setup_routes
  systemd: state=started name=setup_routes enabled=yes

